server:
  port: 9413
spring:
  application:
    name: sleuthprovider
  cloud:
    consul:
      host: 192.168.56.11
      port: 8500
      serviceName: sleuthprovider
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG