server:
  port: 8081
config:
  db:
    ip: 127.0.0.1
    port: 3306
    username: root
    password: root
management:
  health:
    defaults:
      enabled: false
    security:
      enabled: false
health.config.enabled: false
endpoints:
  health:
    sensitive: false