spring:
  cloud:
    consul:
        host: 192.168.56.11
        port: 8500
        discovery:
          serviceName: consulserver
          healthCheckPath: /health
          healthCheckInterval: 15s
          tags: bizi,test
server:
  port: 8083
management.health.consul.enabled: false