spring:
  cloud:
    consul:
        host: http://consul.zhonganonline.com
        port: 8500
        discovery:
          serviceName: consulserver
          healthCheckPath: /health
          healthCheckInterval: 15s
server:
  port: 8083