spring:
  cloud:
    consul:
      host: 192.168.56.11
      port: 8500
      discovery:
        serviceName: consulserver
        healthCheckPath: /health
        healthCheckInterval: 15s
        tags: 1000
server:
  port: 8089
management.health.consul.enabled: false