server:
  port: 8081
spring:
  cloud:
    config:
      server:
        svn:
          uri: http://10.253.101.99:8888/repos/zis/microservices/app/config/
  profiles:
      active: subversion
  application:
    name: configserver