server:
  port: 9412
spring:
  application:
    name: sleuthconsumer
  cloud:
    consul:
      host: 192.168.56.11
      port: 8500
      prefer-ip-address: true
#  zipkin:
#    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG