server:
  port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
spring:
  application:
    name: hystrix
eureka:
  instance:
    metadata-map:
      cluster: MAIN