server:
  port: 8091
eureka:
  instance:
    metadata-map:
      cluster: MAIN
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
spring:
  application:
    name: hystrix
turbine:
  appConfig: hystrix
  aggregator:
    clusterConfig: MAIN
  clusterNameExpression: metadata['cluster']
#turbine的配置缺一不可,缺少后就会出现界面一直loading,无法捕获请求的状态